### ISSUE TITLE
CircularDependencyError between TenantUser and Tenants

### ISSUE THREAD

**Issue by Jromero97** [Corvia/django-tenant-users#14]
Hi! I have some troubles when I'm trying to make migrations, shows me a circular dependency error, anyone knows how solve this problem?

Thanks for help!

**Comment by ivissani** [comment]
Could you please post the details of the error? Your `settings.py`, the error output and the exact command you are executing.

**Comment by Jromero97** [comment]
Ok, I'm executing ./manage.py makemigrations, 
![image](https://user-images.githubusercontent.com/27448401/36264282-f557d01e-1231-11e8-89cb-79aada82fa3b.png)

In my case the tenant is organization and users is TenantUser.
![image](https://user-images.githubusercontent.com/27448401/36264330-11ce5060-1232-11e8-8f96-fa63df1ef5da.png)

![image](https://user-images.githubusercontent.com/27448401/36264355-1f3d8fae-1232-11e8-9678-f2ac70efcf7d.png)
![image](https://user-images.githubusercontent.com/27448401/36264382-2cc9176a-1232-11e8-9666-98355dc7c7d7.png)

In the images you can see my settings..

**Comment by ajmatsick** [comment]
It looks like the circular dependency is due to the tenant and user models being defined in separate apps. The `organization.Organization.owner` field (inherited from `TenantBase`) is related to and therefore depends on `users.TenantUser`. On the other side, the `users.TenantUser.tenants` field (inherited from `UserProfile`) is related to and depends on `organization.Organization`. As such, Django is unable to determine which app's migration should be first. You have a couple options:

1. Move the tenant and user models into the same app, which should allow Django to create the migrations.
2. Manually write migrations for the apps. For example:
    1. `organization.0001_initial` adds the `Organization` model
    2. `users.0001_initial` adds the `TenantUser` model and its `tenants` field with a relationship to `organizations.Organization`
    3. `organization.0002_add_owner_field` adds the `owner` foreign key field to the `Organization` model with a relationship to `users.TenantUser`

**Comment by Jromero97** [comment]
We did in that way and It works! Thanks!
