### ISSUE TITLE
Dont understand how assign another user to tenant

### ISSUE THREAD

**Issue by Ceh9N** [Corvia/django-tenant-users#418]
Hi, i was trying to add another user to tenant by this method - python manage.py create_tenant_superuser --schema=name_of_the_scheme(not public). After executing this command i`ve got this error -  tenant_users.tenants.models.SchemaError: Schema must be public for UserProfileManager user creation
Maybe could somebody help me to solve this problem.

**Comment by Dresdn** [comment]
Hi @Ceh9N - The `create_tenant_superuser` is from the package `django-tenants` and by default just calls Django's "createsuperuser" but within the context of the given tenant.

Since you're using our `UserProfile`, you can see that [there's a check on this](https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/models.py#L243). Ultimately, this can probably be changed as the USER object is in the `SHARED_APPS` and can technically be created from any context. Plus there's also specific checks to pull the public_tenant and perform actions that way ...

Anyways, to answer your question, the best way to create a user would be to use our manager's `create_user()` or `create_superuser()` methods. Take a look at [Creating A User](https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/models.py#L243) in the documentation.

Hope this helps! Let me know if you have other questions.

**Comment by Ceh9N** [comment]
Thanks very much for answer!
