### ISSUE TITLE
RelatedObjectDoesNotExist when removing user

### ISSUE THREAD

**Issue by premudeshi** [Corvia/django-tenant-users#507]
I am trying to remove a user from a Tenant and I get the error `TenantUser has no usertenantpermissions.`

Here is the snippet I am using to remove the user:
```
pk = request.GET.get('pk')
user = TenantUser.objects.get(pk=pk)
tenant = Client.objects.get(pk=request.tenant.pk)
 tenant.remove_user(user)
```

What am I doing incorrect?

**Comment by Dresdn** [comment]
Without a stack trace, I'm going to guess you're seeing the error [on line 134 here](https://github.com/Corvia/django-tenant-users/blob/87c6a09e67bac75f568546fa5f9b90c9b7842891/tenant_users/tenants/models.py#L134C9-L134C9). Is that correct?

Are you removing the `UserTenantPermissions` beforehand? Are you setting them at all? I would also ask how you're adding the user to the tenant as the `Tenant.add_user()` creates the `UserTenantPermissions`, so they *should* be there when attempting to remove.

I suppose this could be refactored to be a little safer in case the `UserTenantPermissions` are removed ahead of time.

**Comment by premudeshi** [comment]
Yes the issue is line 134. 
I am not removing nor setting them. I am adding them like:
```
userT = get_object_or_404(UserTenantPermissions, profile=user)
perm = Permission.objects.get(codename=request.POST.get('codename'))
userT.user_permissions.add(perm)
```
This snippet works. But for some reason removing it doesn't. I will try some variations to see how to remove it.

**Comment by Dresdn** [comment]
Since the removing fails on line 134, then there isn't a `UserTenantPermissions` object for the user within the tenant you're trying to remove the user from. Have you verified the object exists?

**Comment by kusime** [comment]
I am facing same problem now , but i fix this issue by practicing the document way to add new user ,and bind a user to a company. 

1. when you add new user you should use User.objects.create_user
class UserRegisterSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ["id", "username", "email", "password"]
        read_only_fields = ["id"]

    def create(self, validated_data):
        # disable the account activation by default
        validated_data["is_active"] = False
        instance = User.objects.create_user(**validated_data)
        send_activate_email.send(
            sender="UserRegisterSerializer.create",
            request=self.context["request"],
            instance=instance,
        )
        return instance
## by the way you also need to decalre the User manager with the     objects = UserProfileManager() so that you can use that method

2. when create new company(tenant) you should use provision_tenant to create ,this will do batch of stuff behind

3. when bind new user to a company, you should use TenantBase.add_user . this method will link the company-user m2m field , and create a record in UserTenantPermissions in the correct schema. the table name is permissions_usertenantpermissions.
    @action(methods=[HTTPMethod.POST], detail=True)
    def add_user(self, request, pk=None):
        company = self.get_object()
        email = request.data.get("user_email", None)
        if email is None:
            return Response(
                status=status.HTTP_400_BAD_REQUEST, data={"detail": "user_email should not be null"}
            )
        user = User.objects.filter(email=email).first()
        company.add_user(user) 
        return Response(status=status.HTTP_200_OK, data={"detail": "ok"})

# for the transfer_ownership function ,you also make sure the company owner also have record in permissions_usertenantpermissions table ,

by the way , as i tried out , i find the django admin dashboard not calling the recommend method to create an new company or link the user to a company. even thought you override the Model.save() method .

**Comment by Dresdn** [comment]
@kusime - The formatting of your comment is a little off, seems you may have missed a backtick or something.

To your points:

1. Use `User.objects.create_user()` - Yes, this is general good practice, but it's just a helper function that creates the User object and then adds the object to the Public Schema. Honestly, this whole function should be cleaned up a bit as it doesn't make sense to only require it to be run in the public schema, we can set that.
2. Use `provision_tenant()` - 100%. There's extra params set when interfacing with `django-tenants` when creating the tenant.
3. Use `TenantBase.add_user()` - 100%. I think this is what @premudeshi is missing. This adds a `UserTenantPermissions` object within the specific schema and is referenced when removing a user too. If this object doesn't exist, right now we're throwing an error.
4. Admin Dashboard - @kusime, this is a great call out and could maybe be something we add to the documentation. Having a template that can be used as the ModelAdmin that uses all the appropriate calls would be a great thing to have.

**Comment by premudeshi** [comment]
It seems my Django User models messed up the migrations, I am guessing because of incorrectly configured inheritance. 
Deleted migrations and started fresh, it worked.
