### ISSUE TITLE
Create/modify a tenant user in django-admin page

### ISSUE THREAD

**Issue by stonefullstm** [Corvia/django-tenant-users#525]
When AUTH_USER_MODEL is a custom model, features are lost in admin panel and I am not able create users or modify passwords using admin page as the passwords  are not hashed. Does anyone suggest something?

**Comment by Dresdn** [comment]
You'll need to register your user model with the admin site.

https://docs.djangoproject.com/en/dev/topics/auth/customizing/#custom-users-and-django-contrib-admin

```
You will also need to register your custom user model with the admin.
...
However, if your user model extends AbstractBaseUser, you’ll need to define a custom ModelAdmin class.
```

Since we [inherit from `AbstractBaseUser`](https://github.com/Corvia/django-tenant-users/blob/master/tenant_users/tenants/models.py#L356C19-L356C35), you'll need to take that into account.

This would be a great documentation add as we don't have anything around this!

**Comment by stonefullstm** [comment]
Thank you very much for the guidance
