### ISSUE TITLE
The question about the users that will be tenant based

### ISSUE THREAD

**Issue by ArsenNoshkaliuk** [Corvia/django-tenant-users#563]
Hi ! I`ve got an interesting question, i read your docs and got one question. I there a way to make users tenanted base, currently they are only in public schema and that works great, but i my case, i would need to obtain a lot of users(millions) and is there a way to save users per tenant, or maybe to seperate them and not obtain in one single table for whole system. I would glad for any response, ths !

**Comment by Dresdn** [comment]
Hi @ArsenNoshkaliuk - I'm a bit confused of the ask. Are you asking how to set the "default" user to a specific schema instead of the public?

To your other point of millions of users, what's your concern there? This would be more of a database design issue as Postgres can handle millions (or billions) of rows without issue, if designed right.
