### ISSUE TITLE
How does this work? I don't get it.

### ISSUE THREAD

**Issue by MaximilianKindshofer** [Corvia/django-tenant-users#57]
I got everything configured and setup a public tenant.

Is the system account suspended to not have a password and never be used?

When I create a user e.g. via the shell. The user the user can't login to the administrator site even if I declare him superuser.

I want to have users to be able to authenticate to one tenant but not to any other. And I want users to be able to authenticate at all tenants (superusers).

I have no clue how to do this but it seems that this is the right app for it.

So what am I doing wrong?

**Comment by Viatrak** [comment]
A superuser is a per-tenant setting, not global to all tenants. The public tenant is considered a tenant for permissions.

I think you are confusing the difference between authentication (identity verification) and authorization (permissions). This project de-couples authentication from authorization so that authentication is global, but permissions are per tenant (see documentation).
