### ISSUE TITLE
Error on Django 3.2

### ISSUE THREAD

**Issue by createinnovative** [Corvia/django-tenant-users#75]
@Viatrak I have installed django-tenant-users on Django 3.2. However, it is showing the following error:

`django.core.exceptions.ImproperlyConfigured: The app label 'tenant_users.tenants' is not a valid Python identifier.`

I have seen that there is already a commit here of the fix, but these fixes have not been updated on Pypi when you run `pip install django-tenant-users`. May you please update the Pypi package.

**Comment by robertwt7** [comment]
I'm getting this one as well.. 

I think its related to #40

**Comment by gerald9784** [comment]
hey @createinnovative  I had the same issue. It was fixed in the commit 87a878b60a923507c92b1e6ca5df09bf5ef6a530, no release was made as at the time of writing this. 
consider installing django-tenant-users from github.
pip install git+https://github.com/Corvia/django-tenant-users.git@87a878b60a923507c92b1e6ca5df09bf5ef6a530

**Comment by createinnovative** [comment]
Thanks very much @gerald9784 @robertwt7  this was very helpful.
